// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3KY8VReGu1_LpFdw4vZeO17FcdABJSY',
    appId: '1:985331184933:android:c93472be57baaac69d96cc',
    messagingSenderId: '985331184933',
    projectId: 'store-api-7cdfc',
    storageBucket: 'store-api-7cdfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBa-lW4YR-OAoV_CbcxoO7dtvQay6k3c',
    appId: '1:985331184933:ios:1c24c8907ae4dfa79d96cc',
    messagingSenderId: '985331184933',
    projectId: 'store-api-7cdfc',
    storageBucket: 'store-api-7cdfc.firebasestorage.app',
    iosBundleId: 'com.example.train',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQA-zA_ah9uPv6sVMWEY69HW4rVIU2Hyw',
    appId: '1:166453971768:ios:6cec24f54cee7999b00fcd',
    messagingSenderId: '166453971768',
    projectId: 'lafyuu-9bc8d',
    storageBucket: 'lafyuu-9bc8d.firebasestorage.app',
    iosBundleId: 'com.example.train',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfSSiEwb-9wh4iCyTdkT4FK22qMZUhLg',
    appId: '1:166453971768:web:a57ddefc2ac7ad1ab00fcd',
    messagingSenderId: '166453971768',
    projectId: 'lafyuu-9bc8d',
    authDomain: 'lafyuu-9bc8d.firebaseapp.com',
    storageBucket: 'lafyuu-9bc8d.firebasestorage.app',
    measurementId: 'G-C7CWCM31H3',
  );
}